---
# %variable_name% - access to items from Variables section
# exmaple => %file_path
# $ ... - means that this string is expression
# commands
# !transit
# !condition
# !lookup
# !replace
# !transit-data

# $ abc {} abc {} abc
# $ abc {} abc {} abc:dd-mm-yyyy

#Rules:
# - edit this config in SUBLIME or other editor/IDE with good YAML syntax highlighting
# - keep empty line separation between value transitions for easy reading
# - quote expressions which contains YAML's syntax symbols,
#     example1 => SRC[fieldName] to '=> SRC[fieldName]' or "=> SRC[fieldName]" 
#     example2 ${ var } to '${ var }' or "${ var }" 



_examples:
  plain_code1: true   #returns (bool)true
  plain_code2: 234    #returns (int)234
  plain_code3: <field name>    #returns (object)
  plain_code4: (int)SRC[Field name] + (int)SRC[second field]  #returns (int)sum of two fields
  plain_code5: <field name:double>  #returns (double) value from source object's field
  plain_string1: $some value #returns (sting)'some value'
  plain_string2: "$some value" #returns (sting)'some value'
  plain_string3: '$some value' #returns (sting)'some value'
  string_template: "${ SRC[sdf] } abc { SRC[sdf] } abc" #returns result from string interpolation expr. $"{ SRC["sdf"] } abc { SRC["sdf"] } abc" 
  string_template2: "${ %variable% } abc { <sdf> } abc" #returns result from string interpolation expr. $"{ GLOBALS["variable"] } abc { SRC["sdf"] } abc" 



TraceMode: Auto
DefaultDecimalSeparator: ','
SourceBaseDir: G:\My Drive\Client Data Import\eQ

Variables:
  ConnectionString: data source=some_server;Database=some_db;MultipleActiveResultSets=True;App=EntityFramework;User=user;Password=pwd
  asset_country_id: 71
  main_currency_id: 49 
 
  # analysis_date: !GET 'new DateTime(2020,05,31)'
  # analysis_date: !GET 'new DateTime(2020,06,30)'
  # analysis_date: !GET 'new DateTime(2020,07,31)'
  # analysis_date: !GET 'new DateTime(2020,08,31)'
  # analysis_date: !GET new DateTime(2020,09,30)
  analysis_date: !GET new DateTime(2020,10,31)
  analysis_key: !GET '${((DateTime)%analysis_date%):yyyyMM}'
  prev_analysis_key: !GET '${((DateTime)%analysis_date%).AddMonths(-1):yyyyMM}'
  src_path: !GET '$Original files\\{%analysis_date%:yyyy-MM-dd}'
  postfix: !GET '${%analysis_date%:yyyyMM}'


Pipeline:

  - Name: Cities
    Enabled: false
    Source: !csv { Query: !GET '${%src_path%}\\assets_*.csv', Key: <City> }
    Commands:
      - [ !TARGET { Target: !XqDataSource { Query: city, Key: <name> } } ] 

      - [ <City> , !SET name] 

      - [ 71 , !SET country_id] 


  - Name: Assets
    Enabled: false
    Source: !csv { Query: !GET '${%src_path%}\\assets_*.csv', Key: !CONCAT ['%analysis_key%',<Kustannuspaikan numero>]  }
    SaveCount: 100
    Commands:

      - [ !TARGET { Target: !XqDataSource { Query: asset,  Key: !CONCAT [<external_id>] } } ] 

      - [ !CONCAT [ <Rahasto>,'%analysis_key%'], 
          !LOOKUP { Source: !XqDataSource { Query: master_analysis, Key: <external_id>  } }, 
          !SET master_analysis ]

      - [ SRC.Key, !SET external_id ] 

      - [ <Kustannuspaikan numero>, !SET number ] 

      - [ 71 , !SET country_id ] 

      - [ 10 , !SET forecasting_period_years ]  

      - [ "%main_currency_id%" , !LOOKUP { Source: !XqDataSource { Query: currency, Key: <id> } } , !SET currency ]  

      - [ <Kohteen nimi>, !SET name ]  

      - [ <Kaupallinen nimi>, !SET fullname ]  

      - [ <Osoite>, !REPLACE '@empty={null}' , !SET address ]

      - [ <Postinumero>, !SET zip ]  

      - [ <Lisätieto>, !SET description ]  

      - [ <Arvioitsija>, !SET valuator_name ]  

      - [ <Kohdevastaava>, !SET asset_manager_name ]  

      - [ "%asset_country_id%" , !TYPE int , !SET country_id ]  

      - [ <City> , !LOOKUP { Source: !XqDataSource { Query: city, Key: <name> } } , !SET city ]  

      - [ 10 , !LOOKUP { Source: !XqDataSource { Query: cash_flow_template, Key: <id> } } , !SetCashFlowTemplate DataObject ]  

      - [ !CONCAT ['%prev_analysis_key%',<Kustannuspaikan numero>], 
          !LOOKUP { Source: !XqDataSource { Query: asset, Key: <external_id> }, OnNotFound: SkipValue } , 
          !GET 'DataObject[cash_flow_model]',
          !SET cash_flow_model ]  
    
        # WARNING: need to reimport budgets afer this command!
      - [ !InitAssetCommand { ClearForecasts: true } ]  


      - [ <Kaupallinen nimi>, !SetCustomField AssetProperty_Commercial_Name ] 
      - [ <Kohteen status>, !SetCustomField AssetProperty_Status ] 
      - [ <State>, !SetCustomField AssetProperty_State ] 
      - [ <Tyyppi (Kustannuspaikka)>, !SetCustomField AssetProperty_Type ] 
      - [ <Hankintaprosessi>, !SetCustomField AssetProperty_Acquisition_Process ] 
      - [ <Kohdepäällikkö / PM>, !SetCustomField AssetProperty_Property_Manager ] 
      - [ <Omistusosuus kohteesta (%)>, !TYPE decimal, !SetCustomField AssetProperty_Ownership ] 
      - [ <ALV-aste (%)>, !TYPE decimal, !SetCustomField AssetProperty_VAT ] 
      - [ <Vuokrauksen prioriteetti>, !SetCustomField AssetProperty_Leasing_Priority ] 
      - [ <Ylläpidon tyyppi>, !SetCustomField AssetProperty_Maintenance_Type ] 
      - [ <Ylläpitovuokrat>, !SetCustomField AssetProperty_Maintenance_Rents ] 
      - [ <Autopaikat lkm yhteensä>, !TYPE long, !SetCustomField AssetProperty_Parking_Places_Total ] 
      - [ <Paikka lkm (hoiva/päiväkoti)>, !TYPE long, !SetCustomField AssetProperty_Quantity_care_nursery ] 
      - [ <Huoneisto lkm (hoiva)>, !TYPE long, !SetCustomField AssetProperty_Amount_of_Rooms_care ] 
      - [ <Asuntojen lukumäärä>, !TYPE { Type: long, DecimalSeparator: '.'}, !SetCustomField AssetProperty_Amount_of_Flats ] 
      - [ <Myyntiprosessi>, !SetCustomField AssetProperty_Sales_Process ] 
      - [ <Property type>, !SetCustomField AssetProperty_Property_Type ] 
      - [ <Maan omistus>, !SetCustomField AssetProperty_Land_Ownership ] 
      - [ <Vuokralaiskonserni>, !SetCustomField AssetProperty_Tenant_Group ] 
        # ask EQ to provide this field in same format always (with , or . separator)
      - [ <Arviokirja-arvo (hankintahetki)>, !TYPE { Type: long, DecimalSeparator: '.'}, !SetCustomField AssetProperty_External_Market_Value_at_acquisition ] 
      - [ <Arvioitu valmistuminen>, !TYPE DateTime, !SetCustomField AssetProperty_Estimated_Completion_Date ] 
      - [ <Vahvistettu valmistuminen>, !TYPE DateTime, !SetCustomField AssetProperty_Approved_Completion_Date ] 


      - [ !GET? <Vuokratyyppi>,
          !CONCAT [ VALUE, '$Rent Type' ] , 
          !LOOKUP { Source: !excel { Query: mappings.xlsx, Key: !CONCAT [<Source item>,<ModelTree category>] }, OnNotFound: RiseError },
          !GET "DataObject[Model Tree name]",
          !SetCustomField AssetProperty_RentType ] 


      - [ <Kiinteistökohteen tyyppi>,
          !IF "!IsEmpty(VALUE)", 
          !CONCAT [ VALUE, $Segment ] , 
          !LOOKUP { Source: !excel { Query: mappings.xlsx, Key: !CONCAT [<Source item>,<ModelTree category>] }, OnNotFound: SkipValue },
          !GET "DataObject[ModelTree item id]",
          !TYPE int,
          !SET segment_id ] 


      - [ <Region>, 
          !LOOKUP { Source: !XqDataSource { Query: region, Key: <name> } } , 
          !SET region ]

      - [ <Submarket>, 
          !LOOKUP { Source: !XqDataSource { Query: microlocation, Key: <name> } } , 
          !SET microlocation ]

      - [ !CONCAT [<Grades>, 'TARGET[segment_id]'], 
          !LOOKUP { Source: !XqDataSource { Query: asset_grade, Key: !CONCAT [<name>,<segment_id>] }, OnNotFound: Continue} , 
          !SET asset_grade ]

      - [ 0.1 , !TYPE float,!SET valuation_accuracy ]  

      - [ !CONCAT ['%prev_analysis_key%',<Kustannuspaikan numero>], 
          !LOOKUP { Source: !XqDataSource { Query: asset, Key: <external_id> }, OnNotFound: Continue } , 
          !GET 'DataObject?[uuid] ?? TARGET[uuid] ?? Guid()',
          !SET uuid ]  


 