---

TraceMode: Auto
DefaultDecimalSeparator: ','
SourceBaseDir: G:\My Drive\Client Data Import\eQ

Variables:
  ConnectionString: data source=some_server;Database=some_db;MultipleActiveResultSets=True;App=EntityFramework;User=user;Password=pwd
  asset_country_id: 71
  main_currency_id: 49 
  analysis_date: !GET new DateTime(2020,10,31)
  analysis_key: !GET '${((DateTime)%analysis_date%):yyyyMM}'
  prev_analysis_key: !GET '${((DateTime)%analysis_date%).AddMonths(-1):yyyyMM}'
  src_path: !GET '$Original files\\{%analysis_date%:yyyy-MM-dd}'
  



Pipeline:

  - Name: Cities
    Enabled: false
    Source: !csv { Query: !GET '${%src_path%}\\assets_*.csv', Key: <City> }
    Commands:
      - [ !TARGET { Target: !XqDataSource { Query: city, Key: <name> } } ] 

      - [ <City> , !SET name] 

      - [ 71 , !SET country_id] 


